import type { Metadata } from "next";
import { Stack_Sans_Headline } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/ui/themes";
import ConvexClientProvider from "./ConvexClientProvider";
import "./globals.css";
import { cn } from "#/lib/utils";

const stackSansHeadline = Stack_Sans_Headline({
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-stack-sans-headline",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        stackSansHeadline.variable,
        "font-sans",
      )}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider appearance={{ theme: dark }}>
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
